KeyError in line 14 of /home/hade/Desktop/bc_thesis/Snakefile:
'input_file'
  File "/home/hade/Desktop/bc_thesis/Snakefile", line 14, in <module>
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1097, in __getitem__
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1280, in _getitem_tuple
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1000, in _getitem_lowerdim
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1343, in _getitem_axis
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1293, in _get_label
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4082, in xs
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
  File "/home/hade/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
